[workspace]
members=[]
resolver="3"

[workspace.package]
description = "A protocol for websites to work with work providers, which give information about users at work for websites to accept or decline"
license = "CC0-1.0"

[workspace.dependencies]
